### ISSUE TITLE
Missing Panel Options in Grafana 7.3.1 / Panel Version 7.0.4

### ISSUE THREAD

**Issue by excedra** [cloudspout/cloudspout-button-panel#31]
We cannot see the Panel Options in Grafana 7.3.1., Panel Version 7.0.4.
Only the Default Panel Options which are the same for all Panels are shown.

![screenshot](https://user-images.githubusercontent.com/923330/98693205-4d974280-2370-11eb-95d3-234eb0bf47bd.JPG)

How can we fix this?

**Comment by derjust** [comment]
There is an issue in 7.0.3 with Grafana 7.3 
It is fixed in the latest version of the plugin.

As long as [this](https://github.com/grafana/grafana-plugin-repository/pull/756) is not merged into the Grafana mainline, the plugin must be [installed manually.](https://github.com/cloudspout/cloudspout-button-panel#install)
