### ISSUE TITLE
"Cannot read property 'forEach' of undefined" after pressing the button

### ISSUE THREAD

**Issue by kochetov-dmitrij** [cloudspout/cloudspout-button-panel#32]
<img width="1440" alt="Снимок экрана 2020-11-21 в 11 30 40" src="https://user-images.githubusercontent.com/24622840/99871828-8cd65680-2bee-11eb-939a-d793fffd3b34.png">

## Expected Behavior
The same behaviour as on the gif in Readme. No errors in the console, sending the request and showing a check mark instead of the loading animation.

## Current Behavior
JS throws an error "Cannot read property 'forEach' of undefined" after pressing the button with the same config as in the Readme file. The query is not sent and the button gets stuck with 'loading' animation

## Environment
grafana:7.3.2
cloudspout-button-panel:7.0.7
chrome 86.0.4240.198 (mac)

**Comment by derjust** [comment]
This issue is known as #27 and fixed as 550e37d7be1b43f3813680fa59979fd82c655dbf

The new release will be available as soon as this gets merged:
https://github.com/grafana/grafana-plugin-repository/pull/756

Wokarounds till then:
* Manual installation as described in [`README.md`](https://github.com/cloudspout/cloudspout-button-panel#install):
* Add a single (unused) parameter (key/value). The receiving server usually ignores this & it works
